# Generated by Django 5.0.6 on 2024-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=255, verbose_name='State / District')),
                ('town', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=15, verbose_name='Phone Number 1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number 2')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
